{"name": "Проверяем, что курьер не может залогиниться с невалидным логином, запрос возвращает ошибку с кодом 404", "status": "passed", "start": 1727696273288, "stop": 1727696273522, "uuid": "d39a3ba0-c8e4-400d-b69c-b18ef06758e0", "historyId": "3ac3b4e53dde0b4324467a14932c0d1f", "testCaseId": "3ac3b4e53dde0b4324467a14932c0d1f", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_invalid_login_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "hanastasia-mbby"}, {"name": "thread", "value": "14322-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}